// Tests for the Stripe integration's trust boundary: signature
// verification, idempotency, and how a Stripe subscription becomes a plan.
//
// These run entirely offline. Signature verification is tested against
// real signatures generated by the Stripe SDK's own test helper, so it
// exercises the same HMAC code path production uses.

import { describe, expect, it } from "vitest";
import Stripe from "stripe";
import type { PrismaClient } from "@/generated/prisma/client";
import {
  claimWebhookEvent,
  mapSubscription,
  readSupabaseUserId,
  releaseWebhookEvent,
} from "./sync";

const stripe = new Stripe("sk_test_offline_key_for_unit_tests");
const WEBHOOK_SECRET = "whsec_test_secret";
const FOUNDING_PRICE_ID = "price_founding_599";
const REGULAR_PRICE_ID = "price_regular_799";

// A realistic Stripe subscription, shaped the way recent API versions send
// it: the billing period lives on the subscription item, not the top level.
function stripeSubscription(overrides: Record<string, unknown> = {}) {
  return {
    id: "sub_123",
    object: "subscription",
    status: "active",
    customer: "cus_123",
    cancel_at_period_end: false,
    metadata: { supabaseUserId: "user-uuid-1" },
    items: {
      object: "list",
      data: [
        {
          id: "si_123",
          price: { id: FOUNDING_PRICE_ID },
          current_period_start: 1_757_462_400, // 2025-09-10T00:00:00Z
          current_period_end: 1_760_054_400, // 2025-10-10T00:00:00Z
        },
      ],
    },
    ...overrides,
  } as unknown as Stripe.Subscription;
}

describe("webhook signature verification", () => {
  it("accepts a correctly signed payload", () => {
    const payload = JSON.stringify({ id: "evt_1", type: "customer.subscription.updated" });
    const header = stripe.webhooks.generateTestHeaderString({
      payload,
      secret: WEBHOOK_SECRET,
    });

    const event = stripe.webhooks.constructEvent(payload, header, WEBHOOK_SECRET);
    expect(event.id).toBe("evt_1");
  });

  it("rejects a payload signed with the wrong secret", () => {
    const payload = JSON.stringify({ id: "evt_1", type: "customer.subscription.updated" });
    const header = stripe.webhooks.generateTestHeaderString({
      payload,
      secret: "whsec_someone_elses_secret",
    });

    expect(() =>
      stripe.webhooks.constructEvent(payload, header, WEBHOOK_SECRET),
    ).toThrow();
  });

  it("rejects a payload that was altered after signing", () => {
    const payload = JSON.stringify({ id: "evt_1", type: "customer.subscription.updated" });
    const header = stripe.webhooks.generateTestHeaderString({
      payload,
      secret: WEBHOOK_SECRET,
    });
    const tampered = JSON.stringify({ id: "evt_1", type: "customer.subscription.deleted" });

    expect(() =>
      stripe.webhooks.constructEvent(tampered, header, WEBHOOK_SECRET),
    ).toThrow();
  });

  it("rejects a missing signature header", () => {
    const payload = JSON.stringify({ id: "evt_1" });
    expect(() => stripe.webhooks.constructEvent(payload, "", WEBHOOK_SECRET)).toThrow();
  });
});

describe("webhook idempotency", () => {
  // Stands in for the database: `create` throws on a duplicate id, exactly
  // as the primary key does in Postgres.
  function fakePrisma() {
    const seen = new Set<string>();
    return {
      seen,
      client: {
        stripeWebhookEvent: {
          async create({ data }: { data: { id: string } }) {
            if (seen.has(data.id)) throw new Error("duplicate key");
            seen.add(data.id);
            return data;
          },
          async delete({ where }: { where: { id: string } }) {
            seen.delete(where.id);
            return where;
          },
        },
      } as unknown as PrismaClient,
    };
  }

  it("lets the first delivery through", async () => {
    const { client } = fakePrisma();
    expect(await claimWebhookEvent("evt_1", "invoice.payment_succeeded", client)).toBe(true);
  });

  it("blocks a retried delivery of the same event", async () => {
    const { client } = fakePrisma();
    await claimWebhookEvent("evt_1", "invoice.payment_succeeded", client);
    expect(await claimWebhookEvent("evt_1", "invoice.payment_succeeded", client)).toBe(false);
    expect(await claimWebhookEvent("evt_1", "invoice.payment_succeeded", client)).toBe(false);
  });

  it("still lets a different event through", async () => {
    const { client } = fakePrisma();
    await claimWebhookEvent("evt_1", "invoice.payment_succeeded", client);
    expect(await claimWebhookEvent("evt_2", "invoice.payment_succeeded", client)).toBe(true);
  });

  it("lets Stripe retry an event whose handling failed", async () => {
    const { client } = fakePrisma();
    await claimWebhookEvent("evt_1", "customer.subscription.updated", client);
    await releaseWebhookEvent("evt_1", client);
    expect(await claimWebhookEvent("evt_1", "customer.subscription.updated", client)).toBe(true);
  });
});

describe("mapping a Stripe subscription to a plan", () => {
  it("makes an active subscription Pro", () => {
    const fields = mapSubscription(stripeSubscription(), FOUNDING_PRICE_ID);
    expect(fields.plan).toBe("PRO");
    expect(fields.stripeStatus).toBe("active");
    expect(fields.stripeCustomerId).toBe("cus_123");
  });

  it("reads the billing period from the subscription item", () => {
    const fields = mapSubscription(stripeSubscription(), FOUNDING_PRICE_ID);
    expect(fields.currentPeriodStart).toEqual(new Date("2025-09-10T00:00:00Z"));
    expect(fields.currentPeriodEnd).toEqual(new Date("2025-10-10T00:00:00Z"));
  });

  it("falls back to the legacy top-level billing period", () => {
    const legacy = stripeSubscription({
      items: { object: "list", data: [{ id: "si_1", price: { id: REGULAR_PRICE_ID } }] },
      current_period_start: 1_757_462_400,
      current_period_end: 1_760_054_400,
    });
    const fields = mapSubscription(legacy, FOUNDING_PRICE_ID);
    expect(fields.currentPeriodEnd).toEqual(new Date("2025-10-10T00:00:00Z"));
  });

  it("flags a founding-price subscription", () => {
    expect(mapSubscription(stripeSubscription(), FOUNDING_PRICE_ID).isFoundingPrice).toBe(true);
  });

  it("does not flag a regular-price subscription as founding", () => {
    const regular = stripeSubscription({
      items: {
        object: "list",
        data: [{ id: "si_1", price: { id: REGULAR_PRICE_ID }, current_period_end: 1_760_054_400 }],
      },
    });
    expect(mapSubscription(regular, FOUNDING_PRICE_ID).isFoundingPrice).toBe(false);
  });

  it("keeps access through past_due and drops it on cancellation", () => {
    expect(mapSubscription(stripeSubscription({ status: "past_due" }), FOUNDING_PRICE_ID).plan)
      .toBe("PRO");
    expect(mapSubscription(stripeSubscription({ status: "trialing" }), FOUNDING_PRICE_ID).plan)
      .toBe("PRO");
    expect(mapSubscription(stripeSubscription({ status: "canceled" }), FOUNDING_PRICE_ID).plan)
      .toBe("FREE");
    expect(mapSubscription(stripeSubscription({ status: "unpaid" }), FOUNDING_PRICE_ID).plan)
      .toBe("FREE");
    expect(mapSubscription(stripeSubscription({ status: "incomplete" }), FOUNDING_PRICE_ID).plan)
      .toBe("FREE");
  });

  it("records a scheduled cancellation without ending access", () => {
    const fields = mapSubscription(
      stripeSubscription({ cancel_at_period_end: true }),
      FOUNDING_PRICE_ID,
    );
    expect(fields.plan).toBe("PRO");
    expect(fields.cancelAtPeriodEnd).toBe(true);
  });
});

describe("attributing a subscription to a Supabase user", () => {
  it("reads the user ID from subscription metadata", () => {
    expect(readSupabaseUserId(stripeSubscription())).toBe("user-uuid-1");
  });

  it("falls back to the customer's metadata", () => {
    const subscription = stripeSubscription({
      metadata: {},
      customer: { id: "cus_123", object: "customer", metadata: { supabaseUserId: "user-uuid-2" } },
    });
    expect(readSupabaseUserId(subscription)).toBe("user-uuid-2");
  });

  it("returns null rather than guessing when there is no metadata", () => {
    const subscription = stripeSubscription({ metadata: {}, customer: "cus_123" });
    expect(readSupabaseUserId(subscription)).toBeNull();
  });
});
