-- Astro Coach baseline — the pre-Pro schema as it already exists.
--
-- This project's original tables were created by hand rather than through
-- Prisma Migrate, so no migration history was ever recorded and the three
-- legacy migration folders (init, add_question_report, add_bookmark) did
-- not reproduce the real schema: they described TEXT primary keys, while
-- the live columns are PostgreSQL uuid with a gen_random_uuid() default.
-- Those folders are kept for reference in prisma/legacy-migrations/.
--
-- This file was generated by introspecting the live database
-- (prisma migrate diff --from-empty --to-config-datasource), so it
-- reproduces the real column types, precisions, defaults, primary keys,
-- indexes and unique constraints rather than a guess at them.
--
-- It is a BASELINE: on the existing database it is marked as already
-- applied and never executed. It runs only on a genuinely fresh database.
-- It contains no Pro-v1 objects, no Supabase auth or storage internals,
-- no data, and no destructive statements.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "public"."Bookmark" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "userId" TEXT NOT NULL,
    "questionId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Bookmark_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."QuestionReport" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "questionId" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "details" TEXT,
    "userId" TEXT,
    "userEmail" TEXT,
    "status" TEXT NOT NULL DEFAULT 'open',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "QuestionReport_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."UserAttempt" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "userId" TEXT NOT NULL,
    "questionId" TEXT NOT NULL,
    "submittedAnswer" TEXT NOT NULL,
    "isCorrect" BOOLEAN NOT NULL,
    "createdAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UserAttempt_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."UserQuestionProgress" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "userId" TEXT NOT NULL,
    "questionId" TEXT NOT NULL,
    "isCorrect" BOOLEAN NOT NULL,
    "firstCorrectAt" TIMESTAMP(6),
    "lastAttemptAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "attemptCount" INTEGER NOT NULL DEFAULT 0,
    "correctAttemptCount" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "UserQuestionProgress_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Bookmark_userId_idx" ON "public"."Bookmark"("userId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "Bookmark_userId_questionId_key" ON "public"."Bookmark"("userId" ASC, "questionId" ASC);

-- CreateIndex
CREATE INDEX "QuestionReport_questionId_idx" ON "public"."QuestionReport"("questionId" ASC);

-- CreateIndex
CREATE INDEX "QuestionReport_status_idx" ON "public"."QuestionReport"("status" ASC);

-- CreateIndex
CREATE INDEX "UserAttempt_questionId_idx" ON "public"."UserAttempt"("questionId" ASC);

-- CreateIndex
CREATE INDEX "UserAttempt_userId_idx" ON "public"."UserAttempt"("userId" ASC);

-- CreateIndex
CREATE INDEX "UserQuestionProgress_userId_idx" ON "public"."UserQuestionProgress"("userId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "UserQuestionProgress_userId_questionId_key" ON "public"."UserQuestionProgress"("userId" ASC, "questionId" ASC);

